# Generated by Django 3.1 on 2021-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_account', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=2, null=True)),
                ('user_birthday', models.DateField(null=True)),
            ],
        ),
    ]
