# Generated by Django 3.1 on 2021-09-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210127_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_account',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
