# Generated by Django 3.1 on 2021-09-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210927_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucky_award',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=20)),
            ],
        ),
    ]
