# Generated by Django 3.1 on 2021-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_lucky_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_money',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
