# Generated by Django 3.1 on 2021-10-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20211026_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_stores',
            fields=[
                ('stores_id', models.AutoField(primary_key=True, serialize=False)),
                ('stores_name', models.CharField(max_length=20)),
                ('stores_num', models.IntegerField(default=0)),
            ],
        ),
    ]
