# Generated by Django 3.1 on 2021-10-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20211028_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_stores',
            old_name='stores_name',
            new_name='store_name',
        ),
        migrations.RenameField(
            model_name='user_stores',
            old_name='stores_num',
            new_name='store_num',
        ),
    ]
