# Generated by Django 3.1 on 2021-10-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20211028_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_money',
            field=models.IntegerField(default=1000),
        ),
    ]
