# Generated by Django 3.1 on 2021-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20211028_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danmu',
            fields=[
                ('danmu_id', models.AutoField(primary_key=True, serialize=False)),
                ('danmu_name', models.CharField(max_length=255)),
                ('danmu_time', models.DateField(null=True)),
            ],
        ),
    ]
