# Generated by Django 3.1 on 2022-01-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_danmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danmu',
            name='danmu_time',
            field=models.DateTimeField(null=True),
        ),
    ]
