# Generated by Django 3.1 on 2022-01-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20220127_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='danmu',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.user_info'),
        ),
    ]
